version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:8.9 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "npm installing" # run the `echo` command
      - run: npm install
      - run: CI=true npm run build
  test:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:8.9 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "testing stuff" # run the `echo` command
      - run: npm install
      - run: npm test
    hithere:
      docker: # use the docker executor type; machine and macos executors are also supported
        - image: circleci/node:8.9 # the primary container, where your job's commands are run
      steps:
        - checkout
        - run: echo "helloooo!"
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
        requires:
          - hithere
